Display ratings + unique plays on level page
LittleBigRefresh/refresh-web pull request #24
Opened 2023-09-05 14:04 UTC by speedyman09

2023-09-05 19:19 UTC, jvyden requested changes

2023-09-05 19:19 UTC, jvyden commented on src/app/pages/level/level.component.html
> +        <div class="flex items-center"> <i class="fa-solid fa-play pr-1"></i> {{level.uniquePlays}} </div>
Don't one-line these, also we use <fa-icon> instead of <i>.

2023-09-06 11:56 UTC, speedyman09 commented on src/app/pages/level/level.component.html
> +        <div class="flex items-center"> <i class="fa-solid fa-play pr-1"></i> {{level.uniquePlays}} </div>
wdym by don’t one line
the div, or everything?

2023-09-10 23:02 UTC, jvyden commented
This PR has duplicate code from #25, how do you want me to proceed? Close this PR or the other one?

2023-09-11 11:27 UTC, speedyman09 commented
Close this PR and keep #25

2023-09-11 11:29 UTC, jvyden commented
Sure. I believe the two branches diverge due to review comments so I'll merge things into #25 tomorrow.

2023-09-11 11:29 UTC, closed without merging