Team pick icon
LittleBigRefresh/refresh-web pull request #25
Opened 2023-09-05 17:49 UTC by speedyman09

![image](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/85c06969-eb38-45b1-8127-6820d52a36cd)

2023-09-10 23:02 UTC, jvyden requested changes

2023-09-10 23:02 UTC, jvyden commented on package.json
> +    "microtip": "^0.2.2",
Not sure about bringing in an extra library for this. We can definitely achieve this effect ourselves.

2023-09-10 23:02 UTC, jvyden commented on src/app/pages/level/level.component.html
> +        {{ level.title.length == 0 ? 'Unnamed Level' : level.title }} <div *ngIf="level.teamPicked" class="inline" aria-label="This level has been team picked." data-microtip-position="bottom" role="
```suggestion
        {{ level.title.length == 0 ? 'Unnamed Level' : level.title }}
        <div *ngIf="level.teamPicked" class="inline" aria-label="This level has been team picked." data-microtip-position="bottom" role="tooltip">
            <i class="fa-solid fa-circle-check pr-1 fa-xs" ></i><
        /div>
```

2023-09-10 23:02 UTC, jvyden commented on src/app/pages/level/level.component.html
> +        <div class="flex items-center"> <i class="fa-solid fa-play pr-1"></i> {{level.uniquePlays}} </div>
Why are all of these individual flexboxes?

2023-09-11 11:27 UTC, speedyman09 commented on package.json
> +    "microtip": "^0.2.2",
Alright, i’ll look into it

2023-09-11 17:13 UTC, speedyman09 commented on src/app/pages/level/level.component.html
> +        <div class="flex items-center"> <i class="fa-solid fa-play pr-1"></i> {{level.uniquePlays}} </div>
They're all flex because of spacing

With flex:
![image](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/7ffcacfe-6fb8-4123-a944-8bf8d8efc447)
Without flex:
![image](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/1b726bea-4ee0-4f69-ad6c-2aa4a52e6443)

2023-09-11 18:20 UTC, speedyman09 commented
![Screenshot_20230912_002017](https://github.com/LittleBigRefresh/refresh-web/assets/17880243/cb061214-6e4e-4f8d-9810-3107215c24f9)
This is how the new tooltip looks like. Thoughts?

2023-09-11 23:47 UTC, jvyden requested changes
I think it looks good, but I don't like the implications of the CSS behind it.

2023-09-11 23:47 UTC, jvyden commented on src/styles.css
> +}
...Yeah, this won't do. The design looks fine overall, but this approach to CSS has a couple problems:

1. Width/height are hard-coded. This will definitely prevent reusability incase we want to include more tooltips elsewhere.
2. This doesn't use Tailwind meaning we don't have access to common colors such as `form-background`. This prevents us from easily changing the colors. Also, we're using the wrong white for text
3. A lot of these rules are redundant when you consider parent values, for example `font-size` and `font-family`
4. Corners don't match rest of style - use 11px
5. I understand using CSS for complex animations, but again, Tailwind provides these for us.
6. Additionally, this should be a generic Angular element

Visually though, it looks great even if it needs some tweaking - maybe use p-gentle for the text?

2023-09-11 23:53 UTC, jvyden commented on src/app/pages/level/level.component.html
> +          {{level.uniquePlays}}
Also, another thought. We tend to use `<fa-icon [icon]="faIconExample">` for FA icons. These icons aren't guaranteed to be here until we have a direct reference to them somewhere. Meaning if we remove `fa-heart` for example it won't be imported into the resulting build at compile time and it simply won't show up.

Also, formatting is inconsistent here.

2023-09-12 13:10 UTC, speedyman09 commented
I've gotten it working under tailwind. Just a few issues though:
1. the font is incorrect so i have to use font-family to correct it to Rubik
2. for some reason every space that is in the span acts as a newline, and i'm not sure on why that is happening. i didn't mess around with white-space

2023-09-12 13:11 UTC, speedyman09 commented
it might be a parent element that is causing it but even 'white-space: normal' doesn't correct it

2023-09-12 16:35 UTC, speedyman09 commented
https://github.com/LittleBigRefresh/refresh-web/assets/17880243/0290872d-a4c4-40c9-ad95-a91b6e4d7730

2023-09-12 16:37 UTC, speedyman09 commented
The tooltip can now be used anywhere now. To use it, add a 'tooltip-container' class to an element, and add a <tooltip> component as a child to it.

2023-09-12 21:48 UTC, jvyden requested changes
A lot better, just nitpicks at this point

2023-09-12 21:48 UTC, jvyden commented on src/app/pages/level/level.component.html
> +          {{level.uniquePlays}}
These should be direct references to the actual class instead of strings, e.g. `[icon]="faHeart"`

2023-09-12 21:48 UTC, jvyden commented on src/styles.css
> +}
You can achieve this behavior with tailwind, e.g. `hover:opacity-1`

2023-09-12 21:49 UTC, jvyden commented
The font not automatically applying is definitely unintentional behavior so I'll look at it when I get a chance. Ideally there should be 0 CSS rules like the rest of refresh-web.

2023-09-13 12:24 UTC, speedyman09 commented on src/styles.css
> +}
That's not how it works. The goal is to change the opacity of the child '.tooltip' when hovering over 'tooltip-container'.

2023-09-13 12:25 UTC, speedyman09 commented on src/styles.css
> +}
If i put ``` 
hover:opacity-1
```
it won't work

2023-09-16 00:43 UTC, jvyden commented on src/styles.css
> +}
Read some documentation and it looks like it's actually pretty trivial to do this with Tailwind. Using the `group` class on the parent, you can then access it's state with `group-*` (e.g. `group-hover`) in it's children.

https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state

2023-09-16 00:46 UTC, jvyden commented
Removing the request for review since my previous review pass still holds for now.

As a side-note, apologies for the delay. Haven't been feeling well the past couple of days but things have been steadily improving, and this PR should hopefully speed up now :grin:

2023-09-16 05:41 UTC, jvyden approved these changes
I made some changes so it's easier to use from an HTML standpoint, and I'm now pretty happy with how this turned out. I think there's some design changes to be made (e.g. shadowing & better contrast in general) but this can be addressed later after I've played around in Figma enough.

Apologies for the long review process and the dramatic changes necessary it took to get here, but regardless, thank you for the contribution!

2023-09-16 05:42 UTC, merged